### ISSUE TITLE
Allow to rename deleted field through plugin options

### ISSUE THREAD

**Issue by ziishaned** [emiljanitzek/mongoose-delete-ts#19]
Currently, there is no way to rename the deleted at field. I want to rename it to `isDeleted`.

**Comment by emiljanitzek** [comment]
You can add an alias to the `deleted` field to have it mapped to `isDeleted`. You can find an example on how to do this in the [tests](https://github.com/emiljanitzek/mongoose-delete-ts/blob/db131a980b8e5f70b94eb875d56c63c67a47d06d/test/deleted.test.ts#L195). Is this any okay solution or do you need the actual field in the database to be renamed as well?
