### ISSUE TITLE
There is no option to bulk delete (hard delete) documents

### ISSUE THREAD

**Issue by rijin-newage** [emiljanitzek/mongoose-delete-ts#20]
Default `Model.deleteMany()` function is replaced, so there is no option for hard delete documents. There should be a way to pass `force: true` option which will do a hard delete.

```
// Delete multiple object, callback
Model.deleteMany({});

// Delete multiple object (hard), callback
Model.deleteMany({}, { force: true });
```

Note: `Model.remove()` is deprecated.

**Comment by emiljanitzek** [comment]
What is the use-case where you want to use both soft and hard delete for the same model? You could always use the underlying connection to bypass the soft delete for a collection. `mongoose.connection.collection(Model.collection.name).deleteMany({})`

**Comment by viktor21minds** [comment]
so this functionality is essential if you have tests ...you need to clean up otherwise next run will have unique id issues (if you using static user pool without generating them)
